# This is an optional component that can be deployed if the Prometheus Operator is used
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: kubezonnet
    app.kubernetes.io/version: main
  name: kubezonnet-server
  namespace: kubezonnet
spec:
  endpoints:
  - interval: 15s
    port: http
    relabelings:
    - action: labeldrop
      regex: (container|namespace|pod|service)
  selector:
    matchLabels:
      app.kubernetes.io/name: kubezonnet

